### ISSUE TITLE
Kafka server port differs.

### ISSUE THREAD

**Issue by dvdmchl** [OpenLiberty/guide-microprofile-reactive-messaging#162]
In ./scripts/startContainers.bat/sh there is port 9092
In both microprofile-config.properties (in ./system and ./inventory resources/META-INF there is port 9093

**Comment by gkwan-ibm** [comment]
hi @dvdmchl 

Setting microprofile-config.properties to use 9093 that is because of using Kafka test container in integration test. Kafka test container default port is 9093. See https://java.testcontainers.org/modules/kafka.

The startContainers.bat/sh uses bitnami/kafka which default port is 9092. See https://docs.bitnami.com/aws/infrastructure/kafka/get-started/understand-default-config/

**Comment by gkwan-ibm** [comment]
close
- if there is other question, you can reopen this issue or open a new issue
- fyi, the guide was updated to MicroProfile Reactive Messaging 3.0 and replaced the tests to use Testcontainers instead of MicroShed test
