### ISSUE TITLE
Need prereq on how to setup Kafka

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guide-microprofile-reactive-messaging#49]
There should be a section on how to set up Kafka and create the topic required etc.

**Comment by ankitagrawa** [comment]
- That's a great suggestion however we are trying to keep the focus of the guide to reactive messaging as well as trying to keep it simple.
- We do provide link to the Apache Kafka website in the section wherein people can download or learn more about it.
- Also we have a guide dedicated to Kafka in the pipeline.

- Guide already contains multiple microservices and seems complicated at first. Adding Kafka instructions would further complicate things.

Let me know if you feel otherwise. @Emily-Jiang

**Comment by Emily-Jiang** [comment]
I disagree. You need to add prereq section: install Kafka and then create the topics you need.

**Comment by Emily-Jiang** [comment]
In other guides on Kubernetes, there will be a prereq section on how to set up.

**Comment by gkwan-ibm** [comment]
The guide uses the Kafka docker container, no need to install Kafka locally.

**Comment by Emily-Jiang** [comment]
Where is it mentioned in the setup? I might have missed it.

**Comment by gkwan-ibm** [comment]
Yes, it is not that obvious in the bottom of "Building the application" section about running the startContainers.sh to mention Kafka and Zookeeper
- https://draft-guides.mybluemix.net/guides/microprofile-reactive-messaging.html#building-the-application
- http://lgdev1.fyre.ibm.com:4060/guides/microprofile-reactive-messaging.html#building-the-application

The Additional prerequisites section asks to install docker.

**Comment by yeekangc** [comment]
Let us make it obvious and clear to the users then.

**Comment by Emily-Jiang** [comment]
It is important to list the items in the prereq and mention this guide will install Kafka later in the section x.

**Comment by Emily-Jiang** [comment]
Also, some explaination needs to be added from publisher connection channel -> Kafka Topic -> Consumer connection channel.

**Comment by ankitagrawa** [comment]
> Also, some explaination needs to be added from publisher connection channel -> Kafka Topic -> Consumer connection channel.

There is a diagram which explains that connection along with the topic details . And the relation between the channels are explained at various locations throughout the guide.

**Comment by ankitagrawa** [comment]
feedback addressed. Closing this.
